Repository prgrms-web-devcourse/Team-5YES-WuMo-BE, pull requests merged in 2023-02, with the labels that each got.

#1 [WUMO-7] Member 엔티티 구현
  src/main/java/org/prgrms/wumo/domain/member/model/Email.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/member/model/Password.java
Labels: ⚙️ Feature

#2 [WUMO-8] Party 관련 엔티티 구현
  src/main/java/org/prgrms/wumo/domain/party/model/Invitation.java
  src/main/java/org/prgrms/wumo/domain/party/model/Party.java
  src/main/java/org/prgrms/wumo/domain/party/model/PartyMember.java
Labels: ⚙️ Feature

#3 [WUMO-105] Route 엔티티 구현
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/route/model/Route.java
Labels: ⚙️ Feature

#4 [WUMO-9], [WUMO-10] Comment, Location 관련 엔티티 구현
  src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java
  src/main/java/org/prgrms/wumo/domain/comment/model/ContentType.java
  src/main/java/org/prgrms/wumo/domain/comment/model/LocationComment.java
  src/main/java/org/prgrms/wumo/domain/comment/model/PrivateRouteComment.java
  src/main/java/org/prgrms/wumo/domain/comment/model/PublicRouteComment.java
  src/main/java/org/prgrms/wumo/domain/location/model/Category.java
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
Labels: ⚙️ Feature

#5 [WUMO-13] Member API 명세서
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberEmailCheckRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberNicknameCheckRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberGetResponse.java
  src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberRegisterResponse.java
Labels: 📖 Docs

#6 [WUMO-17] Route API 명세서
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteRegisterResponse.java
Labels: 📖 Docs

#8 [WUMO-14] Party API 명세서
  src/main/java/org/prgrms/wumo/domain/party/api/InvitationController.java
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/InvitationRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyGetRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyJoinRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberGetRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/InvitationRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetDetailResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyRegisterResponse.java
Labels: 📖 Docs

#10 [WUMO-19] Image API 명세서
  src/main/java/org/prgrms/wumo/domain/image/api/ImageController.java
  src/main/java/org/prgrms/wumo/domain/image/dto/request/ImageDeleteRequest.java
  src/main/java/org/prgrms/wumo/domain/image/dto/request/ImageRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/image/dto/response/ImageRegisterResponse.java
Labels: 📖 Docs

#13 [WUMO-16] Location API 명세서
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationRegisterResponse.java
Labels: 📖 Docs

#15 [WUMO-124] Logback Spring Profile 설정
  src/main/resources/logback-spring.xml
Labels: 🧷 Config

#16 [WUMO-125] README.md 추가
  README.md
Labels: 📖 Docs

#17 [WUMO-119] TestContainer 설정
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/test/java/org/prgrms/wumo/MysqlTestContainer.java
  src/test/resources/application-test.yml
Labels: 🧷 Config

#18 [WUMO-128] Flyway 및 스키마 초기 설정 보완
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
Labels: 🧷 Config

#19 [WUMO-27] Member 이메일 중복체크 기능 구현
  build.gradle
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberEmailCheckRequest.java
  src/main/java/org/prgrms/wumo/domain/member/model/Email.java
  src/main/java/org/prgrms/wumo/domain/member/repository/MemberRepository.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/exception/ExceptionResponse.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/exception/custom/DuplicateException.java
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/model/EmailTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: ⚙️ Feat, 🧷 Config

#21 [WUMO-133] Route API 명세서 보완
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteStatusUpdateRequest.java
Labels: 📖 Docs

#24 [WUMO-138] Comment API 명세서 보완
  src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PublicRouteCommentGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PublicRouteCommentRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PublicRouteCommentUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/PublicRouteCommentGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/PublicRouteCommentRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/model/PublicRouteComment.java
Labels: 📖 Docs

#22 [WUMO-28] Member 닉네임 중복체크 기능 구현
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/repository/MemberRepository.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: ⚙️ Feat

#23 [WUMO-11] Image 등록, 삭제 기능 구현
  build.gradle
  src/main/java/org/prgrms/wumo/domain/image/api/ImageController.java
  src/main/java/org/prgrms/wumo/domain/image/service/ImageService.java
  src/main/java/org/prgrms/wumo/global/config/AwsConfig.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/exception/custom/ImageDeleteFailedException.java
  src/main/java/org/prgrms/wumo/global/exception/custom/ImageUploadFailedException.java
  src/main/java/org/prgrms/wumo/global/mapper/ImageMapper.java
  src/main/resources/application-prod.yml
  src/test/java/org/prgrms/wumo/domain/image/api/ImageControllerTest.java
  src/test/resources/application-test.yml
Labels: ⚙️ Feat, 🧷 Config

#26 [WUMO-140] Party API 명세서 보완
  src/main/java/org/prgrms/wumo/domain/party/api/InvitationController.java
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/model/Invitation.java
  src/main/java/org/prgrms/wumo/domain/party/model/Party.java
  src/main/java/org/prgrms/wumo/domain/party/model/PartyMember.java
Labels: 📖 Docs

#27 [WUMO-139] 스키마 보완
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/member/model/Email.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/party/model/Invitation.java
  src/main/java/org/prgrms/wumo/domain/party/model/Party.java
  src/main/java/org/prgrms/wumo/domain/route/model/Route.java
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V2__alter_location_change_created_at.sql
Labels: 🐛 Bug

#29 [WUMO-26] Member 회원가입 기능 구현
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberEmailCheckRequest.java
  src/main/java/org/prgrms/wumo/domain/member/model/Email.java
  src/main/java/org/prgrms/wumo/domain/member/model/Password.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/mapper/MemberMapper.java
  src/main/resources/db/migration/V3__alter_all_modify_auto_increment.sql
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: ⚙️ Feat

#32 [WUMO-29] Member 로그인 기능 구현
  build.gradle
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/member/repository/MemberRepository.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtAuthenticationFilter.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
  src/main/java/org/prgrms/wumo/global/jwt/WumoJwt.java
  src/main/java/org/prgrms/wumo/global/mapper/MemberMapper.java
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V4__alter_member_add_refresh_token.sql
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
  src/test/resources/application-test.yml
Labels: ⚙️ Feat

#33 [WUMO-30] Member 로그아웃 기능 구현
  .gitignore
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
  src/test/java/org/prgrms/wumo/domain/member/model/EmailTest.java
Labels: ⚙️ Feat

#31 [WUMO-34] Party 등록 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyRepository.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/model/PartyTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#34 [WUMO-151] Member properties 값 주입 리팩토링
  src/main/java/org/prgrms/wumo/global/config/JwtConfig.java
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
Labels: 🛠 Refactor

#35 [WUMO-38] Party 목록 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetDetailResponse.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#30 [WUMO-37] Location 등록 기능 구현
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/location/repository/LocationRepository.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: ⚙️ Feat

#36 [WUMO-39] Party 상세 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#37 [WUMO-45] Location 상세 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: ⚙️ Feat

#39 [WUMO-165] Security 인증, 인가 관련 예외 구현 및 핸들링
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/java/org/prgrms/wumo/global/exception/custom/CustomAccessDeniedHandler.java
  src/main/java/org/prgrms/wumo/global/exception/custom/CustomAuthenticationEntryPoint.java
Labels: ⚙️ Feat

#38 [WUMO-35] Party 삭제 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#40 [WUMO-169] Member 내 정보 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberGetResponse.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtUtil.java
  src/main/java/org/prgrms/wumo/global/mapper/MemberMapper.java
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: ⚙️ Feat

#43 [WUMO-175] Party 목록 조회 페이지네이션 적용
  build.gradle
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetDetailResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/global/config/QueryDslConfig.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: 🐛 Bug, 🧷 Config

#42 [WUMO-46] Location 목록 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/location/repository/LocationRepository.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
  src/test/java/org/prgrms/wumo/domain/location/LocationTestUtils.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: ⚙️ Feat

#44 [WUMO-52] Route 등록 기능 구현
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/route/model/Route.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteRepository.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#45 [WUMO-181] Party 기능 전역에 로그인 기능 추가 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#47 [WUMO-54] Route 상세 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationResponse.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#46 [WUMO-41] PartyMember 등록 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/InvitationController.java
  src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
  src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
Labels: ⚙️ Feat

#50 [WUMO-56] Route 공개여부 변경 기능 구현
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/model/Route.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#49 [WUMO-43] PartyMember 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
Labels: ⚙️ Feat

#48 [WUMO-79] LocationComment 등록 기능 구현
  src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java
  src/main/java/org/prgrms/wumo/domain/comment/model/LocationComment.java
  src/main/java/org/prgrms/wumo/domain/comment/model/PartyRouteComment.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentRepository.java
  src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
  src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
Labels: ⚙️ Feat, 🐛 Bug

#51 [WUMO-42] PartyMember 수정 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
  src/main/java/org/prgrms/wumo/domain/party/model/PartyMember.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
Labels: ⚙️ Feat

#52 [WUMO-88] 후보지 댓글 목록 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentRepository.java
  src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
  src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
Labels: ⚙️ Feat

#54 [WUMO-57] Route 목록 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponses.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationSimpleResponse.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteRepository.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/java/org/prgrms/wumo/global/mapper/MemberMapper.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/main/resources/db/migration/V5__alter_route_add_desc_index.sql
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#53 [WUMO-40] PartyMember 삭제 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/exception/custom/PartyNotEmptyException.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#58 [WUMO-203] Server port 변경
  src/main/resources/application-prod.yml
Labels: 🧷 Config

#59 [WUMO-205] Location API 명세서 보완
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationSpendingUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationSpendingUpdateResponse.java
Labels: 📖 Docs
