Repository prgrms-web-devcourse/Team-5YES-WuMo-BE, pull requests merged in 2023-03, with the labels that each got.

#61 [WUMO-33] Member 내 정보 수정 기능 구현
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: ⚙️ Feat

#63 [WUMO-53] Route에서 Location 삭제 기능 구현
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: ⚙️ Feat

#64 [WUMO-210] Route API 명세서에 요구사항 변경 반영
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteStatusUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationSimpleResponse.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: 📖 Docs

#65 [WUMO-91] PartyRouteComment 등록 기능 구현
  src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/model/PartyRouteComment.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentRepository.java
  src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
  src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
  src/main/resources/db/migration/V6__alter_party_route_comment_add_location_id.sql
  src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
Labels: ⚙️ Feat

#66 [WUMO-213] NGinx & SSL 인증서 적용
  deploy.sh
  nginx/nginx.conf
  nginx/wumo.conf
  src/main/resources/application-prod.yml
Labels: 🧷 Config

#70 [WUMO-49] Invitation 등록(발급) 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/InvitationController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/InvitationRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/party/model/Invitation.java
  src/main/java/org/prgrms/wumo/domain/party/repository/InvitationRepository.java
  src/main/java/org/prgrms/wumo/domain/party/service/InvitationService.java
  src/main/java/org/prgrms/wumo/global/base62/Base62Util.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/main/resources/db/migration/V7__alter_invitation_drop_code.sql
  src/test/java/org/prgrms/wumo/domain/party/api/InvitationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/InvitationServiceTest.java
Labels: ⚙️ Feat

#73 [WUMO-220] CD 시 로그 충돌 문제 수정
  .github/workflows/ci-cd.yml
Labels: 🐛 Bug, 🧷 Config

#74 [WUMO-62] Route 지역 기준 검색 기능 구현
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#75 [WUMO-230] Route API 명세서에 요구사항 변경 반영
  src/main/java/org/prgrms/wumo/domain/image/dto/request/ImageDeleteRequest.java
  src/main/java/org/prgrms/wumo/domain/image/dto/request/ImageRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/image/dto/response/ImageRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberEmailCheckRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberNicknameCheckRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberGetResponse.java
  src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/InvitationRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteStatusUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponses.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationSimpleResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/route/model/Route.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/main/resources/db/migration/V8__alter_route_add_like_count.sql
Labels: 📖 Docs

#80 [WUMO-229] RouteLike API 명세서 추가
  src/main/java/org/prgrms/wumo/domain/like/controller/RouteLikeController.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyGetRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberGetRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/InvitationRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/InvitationValidateResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyRegisterResponse.java
Labels: 📖 Docs

#78 [WUMO-48] Location 삭제 기능 구현
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: ⚙️ Feat

#84 [WUMO-242] Location API 명세서 형식 정리
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationSpendingUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationSpendingUpdateResponse.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationUpdateResponse.java
Labels: 📖 Docs

#85 [WUMO-241] RefreshToken 저장위치 변경
  build.gradle
  docker-compose.yml
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/member/repository/RefreshTokenRepository.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/config/RedisConfig.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V11__alter_member_drop_refresh_token.sql
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
  src/test/resources/application-test.yml
Labels: 🛠 Refactor

#87 [WUMO-58] RouteLike 등록 기능 구현
  src/main/java/org/prgrms/wumo/domain/like/controller/RouteLikeController.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeRepository.java
  src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java
  src/main/java/org/prgrms/wumo/global/mapper/LikeMapper.java
  src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java
  src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
Labels: ⚙️ Feat

#88 [WUMO-63] RouteLike 삭제 기능 구현
  src/main/java/org/prgrms/wumo/domain/like/controller/RouteLikeController.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeRepository.java
  src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java
  src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java
  src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
Labels: ⚙️ Feat

#77 [WUMO-59] Route 목록 조회 좋아요순 정렬 기능 구현
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/route/dto/request/SortType.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#89 [WUMO-85] LocationComment 삭제 기능 구현
  src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
Labels: ⚙️ Feat

#91 [WUMO-83] PartyRouteComment 수정 기능 구현
  src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentUpdateResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/model/PartyRouteComment.java
  src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
  src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
  src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
Labels: ⚙️ Feat

#92 [WUMO-261] Image 삭제 중 도메인 검증 로직 추가
  src/main/java/org/prgrms/wumo/domain/image/service/ImageService.java
  src/test/java/org/prgrms/wumo/domain/image/api/ImageControllerTest.java
Labels: ⚙️ Feat, 🛠 Refactor

#93 [WUMO-86] PartyRouteComment 삭제 기능 구현
  src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
  src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
Labels: ⚙️ Feat

#94 [WUMO-266] Comment API 명세서 보완 및 용어 정리
  src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentGetAllRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentUpdateResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentGetResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentUpdateResponse.java
Labels: 📖 Docs

#96 [WUMO-257] Member 이메일 인증코드 전송 및 검증 기능 구현
  build.gradle
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberCodeCheckRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/global/config/RedisConfig.java
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/java/org/prgrms/wumo/global/config/properties/JwtProperties.java
  src/main/java/org/prgrms/wumo/global/config/properties/RedisProperties.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/exception/custom/InvalidCodeException.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtAuthenticationFilter.java
  src/main/java/org/prgrms/wumo/global/repository/KeyValueRepository.java
  src/main/java/org/prgrms/wumo/global/repository/RedisRepository.java
  src/main/java/org/prgrms/wumo/global/sender/EmailSender.java
  src/main/java/org/prgrms/wumo/global/sender/Sender.java
  src/main/resources/application-prod.yml
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
  src/test/resources/application-test.yml
Labels: ⚙️ Feat

#97 [WUMO-274] Party 조회 기준 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyGetRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyType.java
  src/main/java/org/prgrms/wumo/domain/party/model/Party.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/model/PartyTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#98 [WUMO-282] Preflight 설정 변경 및 Cors Origin에 프론트 서버 추가
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/resources/application-prod.yml
  src/test/resources/application-test.yml
Labels: 🐛 Bug

#99 [WUMO-273] Party 조회시 구성원 및 전체 멤버 수 포함 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyGetRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/party/model/Party.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#100 [WUMO-280] Member 내 정보 수정 기능 리팩토링
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
Labels: 🛠 Refactor

#102 [WUMO-293] Comment 엔티티 수정
  src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java
  src/main/java/org/prgrms/wumo/domain/comment/model/LocationComment.java
  src/main/java/org/prgrms/wumo/domain/comment/model/PartyRouteComment.java
  src/main/resources/db/migration/V12__alter_comment_drop_is_deleted.sql
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
Labels: 🛠 Refactor

#101 [WUMO-66] RouteLike 집계 스케줄링 (Batch) 기능 구현
  src/main/java/org/prgrms/wumo/batch/like/RouteLikeBatchComponent.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeRepository.java
  src/main/java/org/prgrms/wumo/global/config/BatchConfig.java
Labels: ⚙️ Feat

#103 [WUMO-288] Route 목록 조회 응답 시 좋아요 여부 추가
  src/main/java/org/prgrms/wumo/domain/route/dto/request/SortType.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/route/model/Route.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#104 [WUMO-290] Party 스키마 및 DTO 수정
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyType.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/party/model/Party.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/main/resources/db/migration/V13__alter_party_drop_password.sql
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java
  src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/api/InvitationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/model/PartyTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/InvitationServiceTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: 🛠 Refactor

#105 [WUMO-297] Comment 검증 로직 리팩토링
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java
  src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
  src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
  src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
Labels: 🛠 Refactor

#106 [WUMO-287] Route 상세 조회 기능 요구사항 반영
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/model/Route.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#107 [WUMO-307] Location 실제 사용 금액 갱신 기능 구현
  src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: ⚙️ Feat

#108 [WUMO-313] Party 조회시 fetchJoin 문제 수정
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/repository/InvitationRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/party/service/InvitationService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: 🛠 Refactor

#109 [WUMO-316] Image 서비스 책임 변경
  src/main/java/org/prgrms/wumo/domain/image/repository/ImageRepository.java
  src/main/java/org/prgrms/wumo/domain/image/service/ImageService.java
  src/test/java/org/prgrms/wumo/domain/image/api/ImageControllerTest.java
Labels: 🛠 Refactor

#111 [WUMO-323] Location 수정 및 삭제 권한 변경
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
  src/main/resources/db/migration/V14__alter_location_add_member_id.sql
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/LocationTestUtils.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: 🛠 Refactor

#113 [WUMO-331] YML - 데이터베이스 Batch 관련 옵션 추가
  src/main/resources/application-prod.yml
Labels: 🧷 Config

#112 [WUMO-330] Party 삭제 및 탈퇴 기능 리팩토링
  src/main/java/org/prgrms/wumo/domain/image/repository/ImageRepository.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: 🛠 Refactor

#110 [WUMO-279] Member 회원가입 축하 메일 전송 기능 구현
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/config/AsyncConfig.java
  src/main/java/org/prgrms/wumo/global/config/WebConfig.java
  src/main/java/org/prgrms/wumo/global/event/MemberCreateEvent.java
  src/main/java/org/prgrms/wumo/global/event/listener/MemberEventListener.java
  src/main/java/org/prgrms/wumo/global/repository/RedisRepository.java
  src/main/java/org/prgrms/wumo/global/sender/EmailSender.java
  src/main/java/org/prgrms/wumo/global/sender/Sender.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: ⚙️ Feat

#114 [WUMO-321] 모임 조회 N*2 쿼리 성능 개선
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: 🛠 Refactor

#116 [WUMO-335] Member 내 정보 조회 기능 리팩토링
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/config/WebConfig.java
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: 🛠 Refactor

#115 [WUMO-332] PartyMember 상세 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
Labels: ⚙️ Feat

#118 [WUMO-340] Location 엔티티 수정
  src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
  src/main/java/org/prgrms/wumo/domain/location/model/Category.java
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationResponse.java
  src/main/resources/db/migration/V15__alter_location_change_latitude_latitude_double.sql
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java
  src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
  src/test/java/org/prgrms/wumo/domain/location/LocationTestUtils.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: 🛠 Refactor

#119 [WUMO-322] Route 관심 루트 목록 조회 기능 구현
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#120 [WUMO-349] PartyMember 조회 시 isLeader 필드 추가
  src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetResponse.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
  src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
Labels: ⚙️ Feat

#123 [WUMO-351] Location 상세 조회시 isEditable 필드 추가
  src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
  src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: 🛠 Refactor

#124 [WUMO-354] Comment 상세 조회 응답 DTO isEditable 필드 추가
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentGetResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
  src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
  src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
Labels: 🛠 Refactor

#125 [WUMO-358] Route 공개여부 변경 기능 요구사항 반영
  src/main/java/org/prgrms/wumo/domain/route/model/Route.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#126 [WUMO-365] Comment 정렬 기준 변경
  src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentCustomRepositoryImpl.java
Labels: 🛠 Refactor

#127 [WUMO-370] Party 상세조회 권한 검증 기능 추가 구현
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: 🛠 Refactor

#129 [WUMO-367] Member 이메일 관련 기능 쿼리 튜닝
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/repository/MemberCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/member/repository/MemberCustomRepositoryImpl.java
  src/main/java/org/prgrms/wumo/domain/member/repository/MemberRepository.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: 🛠 Refactor

#128 [WUMO-94] ReplyComment 엔티티 추가 및 등록 기능 구현
  src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/request/ReplyCommentRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/comment/dto/response/ReplyCommentRegisterResponse.java
  src/main/java/org/prgrms/wumo/domain/comment/model/ReplyComment.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/ReplyCommentRepository.java
  src/main/java/org/prgrms/wumo/domain/comment/service/ReplyCommentService.java
  src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
  src/main/resources/db/migration/V19__create_table_if_not_exists_reply_comment.sql
  src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/ReplyCommentServiceTest.java
Labels: ⚙️ Feat

#130 [WUMO-374] Location 실제 사용 금액 수정 권한 변경
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: 🛠 Refactor

#132 [WUMO-379] 공통 예외메시지 Enum으로 관리
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/exception/ExceptionMessage.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: 🧷 Config

#133 [WUMO-383]Route 서비스레이어 가독성 위한 코드 리팩토링
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: 🛠 Refactor

#136 [WUMO-392] Member 비밀번호 변경 기능 구현
  src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberPasswordUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/sender/EmailSender.java
  src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
Labels: ⚙️ Feat

#134 [WUMO-387] PartyMember 등록시 역할 Nullable 허용
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/party/model/Party.java
Labels: 🛠 Refactor

#135 [WUMO-391] Party 예외 메세지 ENUM화
  src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
Labels: 🛠 Refactor

#138 [WUMO-399] RouteLike 집계(Batch) COUNT 0 이슈 수정
  src/main/java/org/prgrms/wumo/batch/like/RouteLikeBatchComponent.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepository.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepositoryImpl.java
Labels: 🐛 Bug

#139 [WUMO-400] Party 수정시 종료일 +1 이슈 해결
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
Labels: 🐛 Bug

#140 [WUMO-401] 공통 예외 핸들러 추가
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
Labels: ⚙️ Feat

#141 [WUMO-406] Image 등록 예외 핸들링 오류 수정
  src/main/java/org/prgrms/wumo/domain/image/repository/ImageRepository.java
Labels: 🐛 Bug

#142 [WUMO-403] Route 상세 조회 리팩토링
  src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
Labels: 🛠 Refactor

#143 [WUMO-388] Route 목록 조회, 검색 기능 성능 개선
  src/main/java/org/prgrms/wumo/domain/route/dto/request/SortType.java
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/cache/CacheType.java
  src/main/java/org/prgrms/wumo/global/config/RedisCacheConfig.java
  src/main/resources/db/migration/V20__alter_route_add_index.sql
  src/main/resources/db/migration/V21__alter_location_add_index_for_search.sql
Labels: 🛠 Refactor

#144 [WUMO-409] Route에 후보지 등록 기능 리팩토링
  src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: 🛠 Refactor

#146 [WUMO-413] Route 상세 조회에 좋아요 기능 반영
  src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
  src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
Labels: ⚙️ Feat

#147 [WUMO-416] Mapper 패키지 구조 수정
  src/main/java/org/prgrms/wumo/domain/comment/mapper/CommentMapper.java
  src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
  src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
  src/main/java/org/prgrms/wumo/domain/comment/service/ReplyCommentService.java
  src/main/java/org/prgrms/wumo/domain/image/mapper/ImageMapper.java
  src/main/java/org/prgrms/wumo/domain/image/service/ImageService.java
  src/main/java/org/prgrms/wumo/domain/like/mapper/LikeMapper.java
  src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java
  src/main/java/org/prgrms/wumo/domain/location/mapper/LocationMapper.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
  src/main/java/org/prgrms/wumo/domain/member/mapper/MemberMapper.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/domain/party/mapper/PartyMapper.java
  src/main/java/org/prgrms/wumo/domain/party/service/InvitationService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/domain/route/mapper/RouteMapper.java
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
  src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Labels: 🧷 Config

#151 [WUMO-423] Route 목록 조회 캐싱 조건 수정
  src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
Labels: 🐛 Bug

#149 [WUMO-419] Comment 예외 메시지 ENUM 적용
  src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java
  src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
  src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
Labels: 🛠 Refactor

#148 [WUMO-418] Location 예외 메시지 ENUM 적용
  src/main/java/org/prgrms/wumo/domain/location/model/Location.java
  src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
Labels: 🛠 Refactor

#153 [WUMO-425] RouteLike 등록 동시성 이슈 해결
  build.gradle
  src/main/java/org/prgrms/wumo/batch/like/RouteLikeBatchComponent.java
  src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java
  src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
Labels: ⚙️ Feat

#155 [WUMO-431] 에러 로그 슬랙 연동
  build.gradle
  src/main/resources/application-log.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring-prod.xml
Labels: ⚙️ Feat

#156 [WUMO-434] 전체 도메인 삭제 이벤트 처리
  src/main/java/org/prgrms/wumo/domain/comment/listener/LocationCommentListener.java
  src/main/java/org/prgrms/wumo/domain/comment/listener/PartyRouteCommentListener.java
  src/main/java/org/prgrms/wumo/domain/comment/listener/ReplyCommentListener.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentRepository.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentRepository.java
  src/main/java/org/prgrms/wumo/domain/comment/repository/ReplyCommentRepository.java
  src/main/java/org/prgrms/wumo/domain/image/listener/ImageListener.java
  src/main/java/org/prgrms/wumo/domain/image/repository/ImageRepository.java
  src/main/java/org/prgrms/wumo/domain/like/listener/RouteLikeListener.java
  src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeRepository.java
  src/main/java/org/prgrms/wumo/domain/location/listener/LocationListener.java
  src/main/java/org/prgrms/wumo/domain/location/repository/LocationRepository.java
  src/main/java/org/prgrms/wumo/domain/party/listener/InvitationListener.java
  src/main/java/org/prgrms/wumo/domain/party/listener/PartyMemberListener.java
  src/main/java/org/prgrms/wumo/domain/party/repository/InvitationRepository.java
  src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java
  src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
  src/main/java/org/prgrms/wumo/domain/route/listener/RouteListener.java
  src/main/java/org/prgrms/wumo/domain/route/repository/RouteRepository.java
  src/main/java/org/prgrms/wumo/global/event/listener/EventListenerIntegrator.java
  src/main/java/org/prgrms/wumo/global/event/listener/JpaEventListener.java
  src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator
  src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
Labels: ⚙️ Feat

#157 [WUMO-339] OAuth(google) 로그인 기능 구현
  build.gradle
  src/main/java/org/prgrms/wumo/domain/member/mapper/MemberMapper.java
  src/main/java/org/prgrms/wumo/domain/member/model/Member.java
  src/main/java/org/prgrms/wumo/domain/member/model/Password.java
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/java/org/prgrms/wumo/global/config/WebConfig.java
  src/main/java/org/prgrms/wumo/global/jwt/CustomAccessDeniedHandler.java
  src/main/java/org/prgrms/wumo/global/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtAuthenticationFilter.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtExceptionFilter.java
  src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
  src/main/java/org/prgrms/wumo/global/oauth/OauthAuthenticationSuccessHandler.java
  src/main/java/org/prgrms/wumo/global/oauth/dto/OauthLoginResponse.java
  src/main/java/org/prgrms/wumo/global/oauth/model/Oauth2Attributes.java
  src/main/java/org/prgrms/wumo/global/oauth/model/SocialOauthType.java
  src/main/java/org/prgrms/wumo/global/oauth/service/CustomOauthService.java
  src/main/java/org/prgrms/wumo/global/sender/EmailSender.java
  src/main/resources/application-security.yml
  src/main/resources/db/migration/V23__alter_member_change_password_null.sql
  src/test/java/org/prgrms/wumo/domain/image/api/ImageControllerTest.java
  src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
  src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
  src/test/resources/application-test.yml
Labels: ⚙️ Feat

#159 [WUMO-438] Security 설정 보완
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
  src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
  src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/wumo/global/exception/custom/InvalidRefreshTokenException.java
Labels: 🧷 Config

#162 [WUMO-444] Token 재발급 이슈 해결
  src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
Labels: 🐛 Bug
